server {
    listen 80;

    server_name megafront.ir www.megafront.ir;

    location / {
        proxy_pass http://shop_frontend:3000;
        include /etc/nginx/proxy_params;
    }

    location /api/ {
        proxy_pass http://shop_backend:3001/;
        include /etc/nginx/proxy_params;
    }
}