server {
   # turn off get website on it's IP
    listen 80 default_server;
    server_name _;

    return 444;
}
server {
   # linking site from ip to domain after aravan cloud + front to 3000 and backend to 3001 in network
    listen 80;
    server_name megafront.ir www.megafront.ir;

        location /api/ {
                proxy_pass https://shop_backend:3001/;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
                proxy_pass https://shop_frontend:3000;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
}